#!/usr/bin/env bash
function destroy() {
    local stack="${1}"
    terraform -chdir="${stack}" destroy "${@:2}"
}

set -e
cd "$(dirname "$0")" || exit 1
destroy "cluster" "${@}"
destroy "nodes" "${@}"
