#!/usr/bin/env bash
function download-qcow2() {
    local FILENAME="debian.qcow2"
    local PATH_DL="${HOME}/Downloads/${FILENAME}"
    local PATH_TMP="/tmp/${FILENAME}"
    if [[ ! -f "${PATH_DL}" ]]; then
        wget \
            https://cloud.debian.org/images/cloud/trixie/latest/debian-13-genericcloud-amd64.qcow2 \
            -O "${PATH_DL}"
    fi
    [[ ! -f "${PATH_TMP}" ]] && cp "${PATH_DL}" "${PATH_TMP}"
}

download-qcow2
